version: '3.8'

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: stack.env
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
      - ./master.sql:/docker-entrypoint-initdb.d/dump.sql
  app:
    image: switchrl/twitchlogger:1.0.1
    container_name: twitchtracker
    restart: unless-stopped
    env_file: stack.env
    ports:
      - 3000:3000
    depends_on:
      - mysqldb

volumes: 
  db-config:
  db-data: